In [1]:
import sys
import numpy as np

# Basic numpy arrays

In [4]:
a = np.array([1, 2, 3, 4]);

In [5]:
b = np.array([0, .5, 1, 1.5, 2]);

In [21]:
a[:], a[1]

(array([1, 2, 3, 4]), 2)

In [13]:
a[0:]

array([1, 2, 3, 4])

In [14]:
a[1:3]

array([2, 3])

In [15]:
a[1:-1]

array([2, 3])

In [23]:
a[1::2] #cada 2 elementos

array([2, 4])

In [24]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [25]:
# multi indexing
b[[0, 2, -1]]

array([0., 1., 2.])

# Array types

In [27]:
a.dtype

dtype('float64')

In [28]:
b.dtype

dtype('float64')

In [29]:
np.array([1, 2, 3, 4],
        dtype = np.float)

array([1., 2., 3., 4.])

In [29]:
np.array([1, 2, 3, 4],
        dtype = np.int8)

array([1., 2., 3., 4.])

In [30]:
c = np.array(['a', 'b', 'c'])

In [32]:
d = np.array([{'a': 1},sys])

In [33]:
d

array([{'a': 1}, <module 'sys' (built-in)>], dtype=object)

In [35]:
d.dtype 

dtype('O')

# Dimensions and shapes

In [36]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]    
])

In [37]:
A.shape

(2, 3)

In [38]:
A.ndim

2

In [39]:
A.size

6

In [42]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1],
    ],
])

In [43]:
B.shape

(2, 2, 3)

In [44]:
B.ndim

3

In [45]:
B.size

12

If the shape isn't consistent, it'll just fall back to regular Python objects:

In [49]:
C = np.array([
    [
    [12, 11, 10],
    [9, 8, 7],
],
[
    [6, 5, 4]
]
])

In [51]:
C.dtype

dtype('O')

In [52]:
C.shape

(2,)

In [53]:
type(C[0])

list

# Indexing and slicing

In [57]:
'''
Square matrix
'''
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
A[1]

array([4, 5, 6])

In [59]:
A[1][0]

4

In [60]:
A[1,0]

4

In [61]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [63]:
A[:2, 2:]

array([[3],
       [6]])

In [64]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
A[1] = np.array([10, 10, 10])

In [66]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [68]:
A[2] = 99

In [97]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

# Summary statistics

In [98]:
a = np.array([1, 2, 3, 4])

In [99]:
a.sum()

10

In [100]:
a.mean()

2.5

In [101]:
a.std()

1.118033988749895

In [102]:
a.var()

1.25

In [109]:
(a.std())**2

1.2500000000000002

In [110]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [111]:
A.sum()

45

In [112]:
A.mean()

5.0

In [113]:
A.std()

2.581988897471611

In [114]:
A.var()

6.666666666666667

In [115]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
A.sum(axis = 0)
# 0 column
# 1 row

array([12, 15, 18])

In [118]:
A.sum(axis = 1)
# 0 column
# 1 row

array([ 6, 15, 24])

In [119]:
print('save')

save
